### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by abikouo**

### CODE REVIEW

**Comment by abikouo** [comment]
rechek

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Review by gravesm — APPROVED** [review]

**Pull request merged**
