### PR TITLE
add step to prepare downstream collection

### PR DESCRIPTION
**Pull request by abikouo**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1507
This is used to build the downstream collection in order to be used for sanity tests on zuul

### CODE REVIEW

**Comment by gravesm** [comment]
Can we not just use the `make downstream-build` target?

**Comment by abikouo** [comment]
> Can we not just use the `make downstream-build` target?

yes I missed this option, but looking at it I am not sure it will fulfill our requirement, I don't know if we can run a sanity test using .tar.gz target?

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Review by gravesm — COMMENTED** [review]
Thanks, this looks good. Can you make sure the integration tests are still passing? I'm fine merging over the prow sanity failures for now, but would like for all the other tests to pass.

**Comment by abikouo** [comment]
> Thanks, this looks good. Can you make sure the integration tests are still passing? I'm fine merging over the prow sanity failures for now, but would like for all the other tests to pass.

integration tests are failing at the configuration step, so this is not something I can fix, it is prow related.
I will just try to retry until I get something green, it may be long

**Pull request merged**
