### PR TITLE
move integration testing to ansible-test (on zuul)

### PR DESCRIPTION
**Pull request by abikouo**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1514

### CODE REVIEW

**Review by gravesm — COMMENTED** [review]
What's the reason for the changes to the files in `module_utils`? It's not obvious why these changes are being included in this PR.

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Pull request closed without merging**
