### PR TITLE
Copy ignore-2.12.txt to ignore-2.13.txt

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Relates to https://github.com/ansible-collections/overview/issues/45#issuecomment-926794724

### CODE REVIEW

**Comment by Andersson007** [comment]
@gravesm looks like CI passed, can we merge this?

**Review by gravesm — APPROVED** [review]
@Andersson007 Thanks for the PR

**Comment by Andersson007** [comment]
@gravesm thanks for reviewing and approving!

**Pull request merged**
