### PR TITLE
enable unit testing

### PR DESCRIPTION
**Pull request by abikouo**
Update unit tests requirements

### CODE REVIEW

**Comment by alinabuzachis** [comment]
@gravesm I guess the units are supposed to run on prow. Is there any benefit to getting them to work on zuul at the moment?

**Comment by gravesm** [comment]
I think the benefits to running on zuul are that we have more control over python and ansible versions. I'm sure this sort of thing would be possible with prow, but definitely easier for us to do it on zuul.

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Review by gravesm — APPROVED** [review]

**Review by alinabuzachis — APPROVED** [review]

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Pull request merged**
