### PR TITLE
Relax kubernetes.core dependency to >= 2.1.0, < 2.4.0

### LINKED ISSUE #148: community.okd breaks Ansible 5 and 6 tests
Currently community.okd requires kubernetes.core 2.1.x or 2.2.x, but Ansible 5 and 6 include kubernetes.core 2.3.0 since Ansible 5.6.0 (released on April 5th). This basically breaks community.okd in Ansible 5.6.0, and this should be fixed ASAP. Right now ansible-core does not check whether the correct versions are installed, but ansible-galaxy does, so installing the collections from Ansible 5.6.0 manually with `ansible-galaxy collection install` is not possible (when using https://github.com/ansible-community/ansible-build-data/blob/main/5/galaxy-requirements.yaml), which in particular makes it impossible to build an Execution Environment for Ansible 5.6.0 (https://github.com/ansible-community/images/pull/22). Please fix this ASAP. The next Ansible 5 release is supposed to happen on April 26th, it would be great if this could be fixed by then.

### PR DESCRIPTION
**Pull request by felixfontein**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1519
Fixes #148. This would be the second choice next to #149. It fixes the current incompatibility.

### CODE REVIEW

**Comment by mariolenz** [comment]
Personally, I prefer #149 over this one. 1) You don't have to adjust your dependencies every time there's a new kubernetes.core version and 2) you _see_ if there's a problem with a newer kubernetes.core release because your CI should tell you.

**Comment by felixfontein** [comment]
The failing tests seem to be unrelated to this PR.

**Comment by abikouo** [comment]
recheck

**Pull request closed without merging**
