### PR TITLE
Prepare 4.0.1 release

### PR DESCRIPTION
**Pull request by seanmalloy**
As a follow up from #243 I am proposing creating release 4.0.1 which contains a single bug fix. If this is merged I can follow up and cherry pick these changes to the main branch.

cc: @HaleCT2

### CODE REVIEW

**Review by GomathiselviS — APPROVED** [review]

**Review by abikouo — APPROVED** [review]

**Comment by GomathiselviS** [comment]
Hi @seanmalloy, [version 4.0.1](https://github.com/openshift/community.okd/releases/tag/4.0.1) is now available. Would you be able to work on cherry-picking these changes to the main branch?

**Comment by seanmalloy** [comment]
> Hi @seanmalloy, [version 4.0.1](https://github.com/openshift/community.okd/releases/tag/4.0.1) is now available. Would you be able to work on cherry-picking these changes to the main branch?

Yes, I'll submit the PR in a few hours. Thanks.

**Comment by seanmalloy** [comment]
@GomathiselviS I have submitted #249

**Pull request merged**
