### PR TITLE
Fix sanity tests

### PR DESCRIPTION
**Pull request by abikouo**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1610
Resole sanity tests errors

### CODE REVIEW

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
> I think we should just remove the python 3.8 unit tests. We have the 3.9 job.

ok I thought to remove it but didn't know if that was intentional, will remove it

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Comment by abikouo** [comment]
recheck

**Review by gravesm — APPROVED** [review]

**Pull request merged**
